---
title: "Script (Data Compilation + Analysis)"
author: "Erik Curtis"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
this.dir = dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(this.dir)

#Packages
library(dplyr)
library(ggpubr)
library(ggsci)
library(Rcpp)
library(reshape)
library(lubridate)
library(naniar)
library(gtools)
library(tidyr)
```

Here, we prepare the raw data (.csv files obtained from the ddPCR machine) for analysis. Positive and negative controls are separated from experimental data, and reactions that failed (i.e. not enough separation between positive and negative droplet clouds) are removed.

```{r Prep Data}
#Create a blank dataframe
Data.Full = data.frame(matrix(nrow= 0, ncol =0))

#Load Data into Data.Full
#'[The "Files" folder must be in the working directory] 
list = list.files(paste(this.dir,"/Files",sep=""))
list <- mixedsort(sort(list))
for (i in 1:length(list)) {
  Data.Full <-rbind(Data.Full, read.csv(paste(this.dir,"/Files/",list[i], sep="") , row.names = ) %>% mutate(Run = i))
}

#Remove unnecessary columns from Quantasoft outputs
Data.Full <- Data.Full %>% select(-c(2,3,5,7,9,11:14,17:21,23:41,43:63))

#Remove failed wells (identified manually by looking at 1-D plot in QuantaSoft)
#Failed reactions are identified by the plate number, and the well coordinates
failed.Rxns <- c("1.F01", "1.F02", "1.F03", "7.C02", "7.C02", "8.C07", "8.C08",
                 "8.C09", "8.F04", "8.F05", "8.F06", "8.C07", "8.C08", "8.C09",
                 "9.B10", "9.B11", "9.B12", "10.C01", "10.C02","10.C03", "10.G04",
                 "10.G05", "10.G06", "10.C10", "10.C11", "10.C12", "10.D10",
                 "10.D11", "10.D12", "14.E07", "14.E08", "14.E09", "16.A04",
                 "16.B04", "16.C04", "18.B06", "18.C05", "18.C06", "18.D06",
                 "18.E05", "18.H04", "16.A01", "16.A02", "16.A03", "16.B01",
                 "16.B02", "16.B03", "14.C07", "14.C08", "14.C09")  
Data.Full <- Data.Full %>% mutate(Run.ID = paste(as.character(Run),Well,sep="."))
Data.Full <- Data.Full %>% replace_with_na(list(Run.ID = failed.Rxns))
Data.Full <- Data.Full %>% na.omit()
Data.Full <- Data.Full %>% select(-c(11))


#Separate experimental data from negative and positive controls
#Information about each ddPCR reaction is encoded in "Sample"
Data.NC <- Data.Full %>% 
  subset(Sample != "Negative_CTL") %>% 
  subset(Sample!= "Positive_CTL") %>% 
  subset(substr(Sample,1,2) != "EB") %>% 
  subset(substr(Sample,1,2) != "CB")

Data.C <- Data.Full %>% 
  subset(Sample == "Negative_CTL" |
         Sample == "Positive_CTL" | 
         substr(Sample,1,2) == "EB" | 
         substr(Sample,1,2) == "CB")

#Data about the sample is encoded in its name
#This will produce an error, but not to worry
Data.NC <- Data.NC %>% 
  cbind(colsplit.character(Data.NC$Sample,
                           split="_", 
                           names = c("Meso.Num", "Time", "Size","Dilution")
                           )
        )

#Separate the release solution from sample data

#BKT = Release Solution/Bucket Data
Data.BKT <- subset(Data.NC, Time == "CARP" | Time == "STHD") 
#NC = Not Control (i.e. sample data)
Data.NC <- subset(Data.NC, Time != "CARP" & Time != "STHD")

#Correct dilution factor for samples that were not diluted, replace with "1"
rem <- c("M1","M2","M3","M4","M5","M6",
         "M7","M8","M9","M10","M11","M12",
         "M13","M14","M15","M16","M17","M18",
         "M19","M20","M21","M22","M23","M24")
Data.NC <- Data.NC %>% 
  replace_with_na(list(Dilution = rem),"1x") 

x <- Data.NC %>% 
  subset(is.na(Dilution)) %>% 
  mutate(Dilution = "1")

Data.NC <- Data.NC %>% subset(!is.na(Dilution))
Data.NC <- rbind(Data.NC, x)
rm(x)

#Some samples were diluted prior to ddPCR, so we need to scale their concentration accordingly.
#We do this by multiplying by the dilution factor
Data.NC <- Data.NC %>% mutate(Concentration = Concentration * as.double(Dilution))

#Combining Technical Replicates
#Any given mesocosm sample is uniquely identified by "Sample" and "Target"
x <- Data.NC %>% group_by(Sample, Target) %>% 
  summarize(Well = "*", Target = first(Target),CopiesPer20uLWell = mean(CopiesPer20uLWell), Positives = sum(Positives), Negatives= sum(Negatives), AcceptedDroplets = sum(AcceptedDroplets), Threshold = mean(Threshold), Run = first(Run), Dilution = first(Dilution))
#Calculate concentration using the probability density function for the Poisson Distribution
#In this formula, 0.000848 is the average volume of a droplet during ddPCR (Given by Quantasoft)
#This is the same calculation that QuantaSoft uses when determining concentration. 
x <- x %>% mutate(Concentration = -log(Negatives/AcceptedDroplets)/0.000848)
#Separate "Sample" again and fix dilution
x <- x %>% cbind(colsplit.character(x$Sample, split="_", names = c("Meso.Num", "Time", "Size")))
x <- x[-c(15)]
x$Dilution <- as.numeric(x$Dilution)
x <- x %>%  mutate(Concentration = Concentration*Dilution)


#Take rows that are still below LOD and assign concentration to 0
y <- x %>% 
  subset((Target == "CARP" & CopiesPer20uLWell <= 3.8 & CopiesPer20uLWell != 0) | (Target == "STHD" & CopiesPer20uLWell <= 3.2 & CopiesPer20uLWell != 0)) %>% 
  mutate(CopiesPer20uLWell = 0, Concentration =0, Well="%")
x <- x %>%  subset((CopiesPer20uLWell > 3.8 & Target == "CARP") | (CopiesPer20uLWell > 3.2 & Target == "STHD") | CopiesPer20uLWell == 0)


#Recombine
Data.NC <- rbind(x,y)
rm(x)
rm(y)


#truncate Concentration
Data.NC$Concentration <- Data.NC$Concentration %>% round_any(accuracy = 0.01, f=floor)

#Filter out BKD samples
Data.BKD <- Data.NC %>% subset(Time == "BKD")
Data.NC <- Data.NC %>% subset(Time != "BKD")

#Get volume filtered for each sample 
#inner-join works basically like VLOOKUP in Excel
Vol.Filtered <- read.csv(paste(this.dir,"/FilteredVolume.csv",sep=""))
Data.NC <- inner_join(Data.NC, Vol.Filtered, by=c('Meso.Num','Time','Size'))

#Calculate Actual Concentration
#This formula varies based on extraction and PCR method, make sure to double check
Data.NC <- Data.NC %>% mutate(GC.mL = (Concentration*1000)/(4*Vol.Filtered.mL))

#Get mesocosm volume + ancillary for each mesocosm
#This datasheet contains DOC, Tempt, pH, turbidity, and most importantly, Mesocosm Volume for each time point
Vol.Meso <- read.csv(paste(this.dir,"/AncillaryFULL.csv",sep=""))
Data.NC <- inner_join(Data.NC,Vol.Meso, by=c("Meso.Num","Time"))


#Calculate Gc per mesocosm
Data.NC <- Data.NC %>% mutate(Gc.mesocosm = GC.mL * Meso.Volume.mL)

#Repeat Process for BKT dataframe
Data.BKT <- Data.BKT %>% dplyr::rename(Bucket = Meso.Num, Rel.soln = Time)
X <- Data.BKT$Dilution
Data.BKT$Dilution <- X %>% replace(X == "BKT1"| X == "BKT2" | X =="BKT3" | X =="BKT4","1")
rm(X)
#Adjust Concentration by dilution
Data.BKT <- Data.BKT %>% mutate(Concentration = Concentration * as.double(Dilution))

#Ignore Carp in STHD buckets and Steelhead in Carp Buckets (usually below LOD anyway)
#Also remove run 15, samples needed diluting, positive cloud was too dense
Data.BKT <- Data.BKT %>% subset(Target == Rel.soln & Run != 15 & Run != 13)

#Calculate true concentration (Vol. Filtered was 100mL for every sample)
Data.BKT <- Data.BKT %>% mutate(GC.mL = (Concentration*1000)/(4*100))

#Export Data Frames as .csv
write.csv(Data.BKD, file="LeafMesos-BKD.csv")
write.csv(Data.C, file="LeafMesos-Controls.csv")
write.csv(Data.BKT, file="LeafMesos-ReleaseSolution.csv")
write.csv(Data.NC, file="LeafMesos-Mesoscosms.csv")




```
